//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlAbstraction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlAbstraction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute already exists..
        /// </summary>
        internal static string XmlObject_Attribute_Already_Exists {
            get {
                return ResourceManager.GetString("XmlObject_Attribute_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory in filename was not found..
        /// </summary>
        internal static string XmlObject_Directory_Not_Found {
            get {
                return ResourceManager.GetString("XmlObject_Directory_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elementname does not exist in the xml, in pending edits, or was already deleted..
        /// </summary>
        internal static string XmlObject_Element_Already_Deleted {
            get {
                return ResourceManager.GetString("XmlObject_Element_Already_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element already exists..
        /// </summary>
        internal static string XmlObject_Element_Already_Exists {
            get {
                return ResourceManager.GetString("XmlObject_Element_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element trying to be read does not exist..
        /// </summary>
        internal static string XmlObject_Element_Does_Not_Exist {
            get {
                return ResourceManager.GetString("XmlObject_Element_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elementname or attributename does not exist in the xml, in pending edits, or was already deleted..
        /// </summary>
        internal static string XmlObject_Element_Or_Attribute_Already_Deleted {
            get {
                return ResourceManager.GetString("XmlObject_Element_Or_Attribute_Already_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is read-only..
        /// </summary>
        internal static string XmlObject_Instance_Read_Only {
            get {
                return ResourceManager.GetString("XmlObject_Instance_Read_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parrent element trying to be read does not exist..
        /// </summary>
        internal static string XmlObject_Parrent_Element_Does_Not_Exist {
            get {
                return ResourceManager.GetString("XmlObject_Parrent_Element_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subelement trying to be read does not exist..
        /// </summary>
        internal static string XmlObject_Subelement_Does_Not_Exist {
            get {
                return ResourceManager.GetString("XmlObject_Subelement_Does_Not_Exist", resourceCulture);
            }
        }
    }
}
