//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elskom.Generic.Libs.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Elskom.Generic.Libs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string KOMManager_Unpacking_KOM_File_Failed {
            get {
                return ResourceManager.GetString("KOMManager_Unpacking_KOM_File_Failed", resourceCulture);
            }
        }
        
        internal static string ExecutionManager_Cannot_Find_x2_exe {
            get {
                return ResourceManager.GetString("ExecutionManager_Cannot_Find_x2_exe", resourceCulture);
            }
        }
        
        internal static string ExecutionManager_ElsDir_Not_Set {
            get {
                return ResourceManager.GetString("ExecutionManager_ElsDir_Not_Set", resourceCulture);
            }
        }
        
        internal static string ExecutionManager_Cannot_Find_elsword_exe {
            get {
                return ResourceManager.GetString("ExecutionManager_Cannot_Find_elsword_exe", resourceCulture);
            }
        }
        
        internal static string KOMManager_Unkown_KOM_Version {
            get {
                return ResourceManager.GetString("KOMManager_Unkown_KOM_Version", resourceCulture);
            }
        }
        
        internal static string KOMManager_Plugin_No_Unpacker_Function {
            get {
                return ResourceManager.GetString("KOMManager_Plugin_No_Unpacker_Function", resourceCulture);
            }
        }
        
        internal static string KOMManager_Packing_KOM_File_Failed {
            get {
                return ResourceManager.GetString("KOMManager_Packing_KOM_File_Failed", resourceCulture);
            }
        }
        
        internal static string KOMManager_Plugin_No_Packer_Function {
            get {
                return ResourceManager.GetString("KOMManager_Plugin_No_Packer_Function", resourceCulture);
            }
        }
        
        internal static string KOMManager_Folder_Version_Check_Error {
            get {
                return ResourceManager.GetString("KOMManager_Folder_Version_Check_Error", resourceCulture);
            }
        }
    }
}
