//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elskom.Generic.Libs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elskom.Generic.Libs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string PluginUpdateCheck_CheckForUpdates_Error {
            get {
                return ResourceManager.GetString("PluginUpdateCheck_CheckForUpdates_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download the plugins sources list.{0}Reason: {1}.
        /// </summary>
        internal static string PluginUpdateCheck_CheckForUpdates_Failed_to_download_the_plugins_sources_list_Reason {
            get {
                return ResourceManager.GetString("PluginUpdateCheck_CheckForUpdates_Failed_to_download_the_plugins_sources_list_Rea" +
                        "son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install the selected plugin.{0}Reason: {1}.
        /// </summary>
        internal static string PluginUpdateCheck_Install_Failed_to_install_the_selected_plugin_Reason {
            get {
                return ResourceManager.GetString("PluginUpdateCheck_Install_Failed_to_install_the_selected_plugin_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New plugin update..
        /// </summary>
        internal static string PluginUpdateCheck_ShowMessage_New_plugin_update {
            get {
                return ResourceManager.GetString("PluginUpdateCheck_ShowMessage_New_plugin_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} for plugin {1} is availible..
        /// </summary>
        internal static string PluginUpdateCheck_ShowMessage_Update_for_plugin_is_availible {
            get {
                return ResourceManager.GetString("PluginUpdateCheck_ShowMessage_Update_for_plugin_is_availible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to uninstall the selected plugin.{0}Reason: {1}.
        /// </summary>
        internal static string PluginUpdateCheck_Uninstall_Failed_to_uninstall_the_selected_plugin_Reason {
            get {
                return ResourceManager.GetString("PluginUpdateCheck_Uninstall_Failed_to_uninstall_the_selected_plugin_Reason", resourceCulture);
            }
        }
    }
}
