//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newsmake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("newsmake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}	{2}.
        /// </summary>
        internal static string CommandParser_ShowHelp {
            get {
                return ResourceManager.GetString("CommandParser_ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:.
        /// </summary>
        internal static string CommandParser_ShowHelp_Available_commands {
            get {
                return ResourceManager.GetString("CommandParser_ShowHelp_Available_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, visit {0}.
        /// </summary>
        internal static string CommandParser_ShowHelp_For_more_information__visit {
            get {
                return ResourceManager.GetString("CommandParser_ShowHelp_For_more_information__visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: {0} &lt;command&gt;.
        /// </summary>
        internal static string CommandParser_ShowHelp_usage {
            get {
                return ResourceManager.GetString("CommandParser_ShowHelp_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string CommandParser_ShowHelp_Version {
            get {
                return ResourceManager.GetString("CommandParser_ShowHelp_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal: Environment variable does not exist..
        /// </summary>
        internal static string Commands_BuildCommand_Fatal__Environment_variable_does_not_exist {
            get {
                return ResourceManager.GetString("Commands_BuildCommand_Fatal__Environment_variable_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal: generated output file name not set..
        /// </summary>
        internal static string Commands_BuildCommand_Fatal__generated_output_file_name_not_set {
            get {
                return ResourceManager.GetString("Commands_BuildCommand_Fatal__generated_output_file_name_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal: no *.master file found..
        /// </summary>
        internal static string Commands_BuildCommand_Fatal__no___master_file_found {
            get {
                return ResourceManager.GetString("Commands_BuildCommand_Fatal__no___master_file_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal: Project name not set..
        /// </summary>
        internal static string Commands_BuildCommand_Fatal__Project_name_not_set {
            get {
                return ResourceManager.GetString("Commands_BuildCommand_Fatal__Project_name_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}....
        /// </summary>
        internal static string Commands_BuildCommand_Processing {
            get {
                return ResourceManager.GetString("Commands_BuildCommand_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Generated &apos;{0}&apos;..
        /// </summary>
        internal static string Commands_BuildCommand_Successfully_Generated {
            get {
                return ResourceManager.GetString("Commands_BuildCommand_Successfully_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bug.
        /// </summary>
        internal static string Commands_Formatline_bug {
            get {
                return ResourceManager.GetString("Commands_Formatline_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvokeOption_Calling_InvokeCommand_on_a_object_with_no_code {
            get {
                return ResourceManager.GetString("InvokeOption_Calling_InvokeCommand_on_a_object_with_no_code", resourceCulture);
            }
        }
    }
}
